# Generated by Django 6.0.1 on 2026-01-28 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0005_alter_user_birth_date_following_thru_unique_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(validators=[django.core.validators.MaxLengthValidator(150)])),
                ('commented_date', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='app_users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_like_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('comment_liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked', to='app_users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='liked_comment', through='post.CommentLike', to='app_users.profile'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('image_content', models.ImageField(blank=True, upload_to='post_pics/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='app_users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('post_liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='app_users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_post', through='post.PostLike', to='app_users.profile'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(validators=[django.core.validators.MaxLengthValidator(50)])),
                ('replied_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied', to='app_users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_like_date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.reply')),
                ('reply_liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_liked', to='app_users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_like',
            field=models.ManyToManyField(blank=True, related_name='liked_reply', through='post.ReplyLike', to='app_users.profile'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment_liked_by', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post_liked_by', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddConstraint(
            model_name='replylike',
            constraint=models.UniqueConstraint(fields=('reply_liked_by', 'reply'), name='unique_user_reply_like'),
        ),
    ]
