# Generated by Django 6.0.1 on 2026-01-29 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_profile_created_date_alter_user_birth_date'),
        ('post', '0002_reply_parent_reply_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_date',
            new_name='made_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_made_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
    ]
