# Generated by Django 6.0.1 on 2026-01-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_posted_date_post_made_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
