# Generated by Django 6.0.1 on 2026-01-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_profile_created_date_alter_user_birth_date'),
        ('post', '0004_post_modification_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_user_post_like',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_date',
            new_name='made_at',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post_like_date',
            new_name='made_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_made_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_made_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='postlike',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='post.comment'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('made_by', 'post'), name='unique_user_post_like'),
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post_liked_by',
        ),
    ]
