# Generated by Django 6.0.1 on 2026-01-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_profile_created_date_alter_user_birth_date'),
        ('post', '0005_remove_postlike_unique_user_post_like_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentlike',
            name='unique_user_comment_like',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_like_date',
            new_name='made_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='replied_date',
            new_name='made_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replied_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_like',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_made_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_made_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reply',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
        migrations.AlterField(
            model_name='replylike',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to='post.reply'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('made_by', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment_liked_by',
        ),
    ]
