# Generated by Django 6.0.1 on 2026-02-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_user_birth_date'),
        ('post', '0006_remove_commentlike_unique_user_comment_like_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentlike',
            name='unique_user_comment_like',
        ),
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_user_post_like',
        ),
        migrations.RemoveConstraint(
            model_name='replylike',
            name='unique_user_reply_like',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='made_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='made_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='made_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='made_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='made_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='replylike',
            old_name='reply_like_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='made_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='reply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='replylike',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='replylike',
            name='modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='replylike',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='replylike',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='app_users.profile'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('created_by', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('created_by', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddConstraint(
            model_name='replylike',
            constraint=models.UniqueConstraint(fields=('created_by', 'reply'), name='unique_user_reply_like'),
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='reply_liked_by',
        ),
    ]
