# Generated by Django 6.0.1 on 2026-02-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_comment_created_by_alter_comment_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
    ]
