# Generated by Django 6.0.1 on 2026-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_following_thru_profile_following_thru_from_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-pic.webp', upload_to='profile_pics/'),
        ),
    ]
