# Generated by Django 6.0.1 on 2026-01-28 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_user_age_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2008, 1, 28)),
        ),
        migrations.AddConstraint(
            model_name='following_thru',
            constraint=models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='unique_follow'),
        ),
    ]
