# Generated by Django 6.0.1 on 2026-02-05 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_remove_profile_profile_pic_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2008, 2, 5)),
        ),
    ]
